export type BlogPost = {
  id: string;
  image: string;
  title: string;
  subtitle?: string;
  paragraphs: string[];
};

export const blogPosts: BlogPost[] = [
  {
    id: "01",
    image: "/images/blog1.jpg",
    title: "La cuestión del Otro en psicoanálisis",
    subtitle: "Lenguaje, sujeto y determinantes sociales",
    paragraphs: [
      "Una premisa fundamental en los psicoanálisis orientados según los postulados de Lacan es la idea de que el sujeto no se funda solo, no es un organismo, entidad o estructura autónoma. La idea del \u201cself-made man\u201d (el hombre hecho o construido por sí mismo) es así problematizada y delatada como ilusoria a partir del análisis del síntoma y las producciones del inconsciente de Freud y Lacan, al revelar que, por una parte, la imagen vacila y quien mira y habla es siempre otro que lo visto y escuchado, y por otra, al relevar la indisolubilidad de lo propio y lo otro en la palabra y en el deseo.",
      "El concepto de Otro viene a dar cuenta de ese terreno, de ese campo en el que el sujeto viene a emerger y a constituirse incesantemente, enfatizando la propiedad de dicho campo como hecho de lenguaje. El Otro es conceptualizado en la teoría lacaniana como el Otro del lenguaje, el \"tesoro de los significantes\". Con esto se enfatiza la primeridad del lenguaje respecto del sujeto. El lenguaje antecede al sujeto, lo determina y condiciona su devenir. Venimos a un mundo ya significado y ya significados en cuanto sujetos. Esta noción fundamental una práctica: el sujeto responde a un Otro que desconoce, al cual se dirige y con respecto al cual se orienta y posiciona, lo cual el análisis viene a conmover y transformar.",
      "Este postulado, novedoso y contrahegemónico —en tanto cuestiona la noción naturalizada de individuo autónomo propia de la cultura contemporánea e incluso del campo psi—, si bien muy potente y útil, por su carácter abstracto y operacionalizable para distintos textos, puede, según se lo interprete y aplique, hacer omisión respecto de condiciones que ineludiblemente determinan el malestar, la subjetividad y lo social: condiciones materiales, socioeconómicas, sociopolíticas, educacionales, discursivo-ideológicas, raciales, sexo-genéricas, entre otras.",
      "¿Es realmente posible una práctica clínica abstraída de tales determinantes de la vida social humana? El problema se da aquí entre una determinada teorización del lenguaje y su relación con los dominios señalados. Como si se pensara que existe el lenguaje, comprendido como un sistema abstracto, con una lógica propia, independiente y autosuficiente, por una parte, y la economía, la política, la ideología (entendida en un sentido amplio que engloba las dimensiones antes señaladas), por otro. ¿No están todos estos dominios, en realidad, íntimamente ligados?",
      "Toda cultura y sociedad produce, administra y fija lo decible y las ideas que tienen valor, en cuyos márgenes se sitúa lo no decible o aquellas ideas que son devaluadas o no reconocidas. Los discursos sociales, entendidos en un sentido abarcativo como esa gran masa de ideas respecto al mundo, que lo configuran y sostienen como tal, son considerados de valor cuando son funcionales a determinada cultura y sociedad, porque permiten el mantenimiento de sus lógicas estructurales. Tales lógicas estructurales, que determinan la supervivencia y reproducción de la sociedad tienen su base en el funcionamiento económico-político.",
      "Este funcionamiento extiende sus lógicas a todas las dinámicas de la vida social, incluyendo las relaciones humanas. ¿Cómo se lleva a cabo el aseguramiento de ese funcionamiento? Mediante discursos, mediante ideas. Las ideas que aseguran la reproducción de las lógicas imperantes son aquellas que se reproducen, normalizan y conforman el núcleo de sentido de la vida social. Aquellas que no, son marginalizadas.",
      "Es así que los lenguajes en circulación están determinados por los factores económico-políticos de la cultura. Una de las ideas más fuertes de nuestra época, por su funcionalidad a la lógica de producción de nuestra cultura, y pertinente por ser la antípoda del postulado de Otro del psicoanálisis, es la del individuo como proyecto económico. Según este mito —no en cuanto falsedad, sino en cuanto configura un mundo, una cosmovisión, un sistema de relaciones— cada individuo debe buscar su desarrollo y mejoramiento continuos por todas las vías posibles y con base en su voluntad, perseverancia y tenacidad para conseguir el éxito, el cual siempre se refiere al aumento del patrimonio económico, la acumulación y el consumo.",
      "Es interesante este ejemplo porque muestra de manera bastante transparente de qué manera el sistema capitalista produce discursos funcionales a sus propios intereses. Un sujeto que produzca permanente e incansablemente, cuya idea de desarrollo sea sólo pensable en términos económicos y que además se piense como autónomo, inmune a su contexto, no limitado por coerciones externas. El desconocimiento de lo otro, la fantasía del individuo autónomo y autosuficiente se construye discursivamente y opera como ideología, como naturalización de un estado de cosas.",
      "En la clínica —en particular la psicoanalítica—, el problema de las determinantes socioeconómicas, políticas e ideológicas son insoslayables si pretendemos fundamentarnos en un paradigma no individualista. Pensar que estas no influyen en el malestar en los vínculos es, aunque se ignore, una posición política y ética desde la cual se mira al sujeto y su malestar. Si se las deja fuera del consultorio y se hace pasar sólo al que padece, se termina hablando la misma lengua que la del sistema capitalista neoliberal. Nuestra pregunta es: ¿En qué lengua responde el psicoanálisis?",
    ],
  },
  {
    id: "02",
    image: "/images/blog2.jpg",
    title: "La palabra como fundamento del trabajo psicoanalítico",
    subtitle: "Exploración, vínculo y producción de novedades",
    paragraphs: [
      "El modo de trabajo en psicoanálisis toma como materia y tema del trabajo la palabra de quien consulta. Aquello que se presenta, en un primer momento —en una primera consulta—, como la problemática o el motivo de consulta, eso que lleva a recurrir a alguien, es inseparable de los términos mismos en que es formulado. Es inseparable precisamente porque se constituye solamente como problemática o malestar en la medida en que la persona que habla se encuentra interpelada e involucrada de una manera determinada, específica y particular con aquello que la aqueja.",
      "A su vez, esa manera particular en la que el sujeto se relaciona con tal problemática o malestar —lo que podemos llamar su posición— a menudo puede estar compuesta y determinada no únicamente por un factor, un solo argumento, o una sola serie de ideas en torno a un tema; sino que estos suelen ser múltiples y, precisamente por confluir como una red en la problemática, la sostienen en cuanto tal para ese sujeto.",
      "Por eso es crucial explorar esa red, esas múltiples dimensiones que pueden estar jugándose en la problemática. La idea de una terapia focalizada, la idea de una intervención breve pensada como la operación precisa y eficaz que bien podría realizar un mecánico sobre la tuerca de un motor con problemas, resulta por ese motivo ingenua: podría estar descuidando aquello que una revisión exhaustiva y minuciosa del asunto a menudo podría encontrar.",
      "Una exploración exhaustiva y detallada de aquello de lo que se trata puede llevar un tiempo —que tampoco debe ser un tiempo infinito—, tiempo que es ya parte del tratamiento. En primer lugar, porque permite la consolidación de un vínculo que sostenga el trabajo. En segundo lugar, porque la exploración tiene el carácter de una investigación que, como tal, comienza a modificar la formulación misma de lo que inicialmente se concebía como problema o malestar; el problema comienza a verse como algo diferente de aquello que en un principio se creía.",
      "En ese sentido, lo que debería ocurrir en el curso del trabajo es la producción de novedades: aperturas de posibilidades, opciones allí donde antes no las había; ausencia allí donde algo insistía y aquejaba. El trabajo interviene como una progresiva modificación del valor de los elementos en juego en los distintos argumentos convergentes.",
      "¿Qué es hacer un psicoanálisis? Una posible respuesta sería: ir a vérnosla con las palabras en que vivimos.",
      "El lenguaje es soporte de la subjetividad. La subjetividad es efecto del lenguaje. Y el lenguaje implica siempre una dialéctica con los otros: es inherentemente social. El síntoma, al entrar en el dominio del discurso, revela una problemática más amplia: la problemática del sujeto en su lazo con el otro en el lenguaje. Por eso, una terapéutica que no incluya el trabajo del lazo social en y por el lenguaje resulta ingenua, de corto alcance y tendenciosa.",
    ],
  },
];
